[package]
name = "pubip"
version = "0.1.0"
authors = ["Andreas Henriksson <andreas@fatal.se>"]
edition = "2018"

[dependencies]
ureq = "0.12.1"
#dnssector = "0.1.3"
dnssector = { git = "https://github.com/andhe/dnssector.git" }
